### PR TITLE
cash target guidelines

### PR DESCRIPTION
**Pull request by bluquar**
Show lines for the "target" of the amount of cash we want. In the next PR I'll add rules that attempt to keep the cash within the target amount.
Screen Shot 2022-05-02 at 12 53 09 PM

### CODE REVIEW

**Comment by lowellbander** [comment]
does this mean cash as in what's in a checking or savings account? how do
you determine how much cash to have? how do you balance cash against
investments which throw off dividends/interest and can be sold piecemeal as
they appreciate?

**Comment by bluquar** [comment]
yes, what's in a checking or savings account. the goal is to have 5-6 years of expenses in cash. any excess will go into investments (not yet implemented). if cash gets too low, then investments will be sold (not yet implemented).

**Comment by lowellbander** [comment]
How'd you come up with 5-6 years?

I don't have a number personally, right now I have 3 years in cash just
because I happen to have it, but I'm gonna try to read enough about
investing strategies that I feel comfortable having less cash so that I
don't miss out on all the potential investment gains

**Comment by bluquar** [comment]
You told me 5 years because the market can go up and down so you generally wouldn't want to sell when it's at a lower point.

Another way of looking at it though is that, let's say your expenses are $5000/mo, then if 4% of your investments comes out to $10000/mo, then it shouldn't matter even if the market goes down? Maybe? Since even if you take 4% out and the market goes down 20%, you're still above the amount of investments you would need to withdraw 4% per year? Idk, I'm pretty confused. But what I'm getting at is that the greater your investments are, the less risk there is of you running out of cash if the market crashes, because your investments will still be worth a lot even if the market crashes, so you can keep selling some of them off?

**Comment by lowellbander** [comment]
That 5 years notion was lifted from "Quit Like a Millionaire
<https://www.penguinrandomhouse.com/books/592323/quit-like-a-millionaire-by-kristy-shen-and-bryce-leung-foreword-by-jl-collins/>",
and I'm still pretty ignorant on market histories, but I think there have
been times when it took longer for the market to recover, so I'm not sure
what to make of this. The 4% rule is based on withdrawing 4% every year
regardless of market conditions, and that yields a 95% success rate, which
means 5% of the time you run out of money before you run out of life, but
that assumes
<https://www.mrmoneymustache.com/2012/05/29/how-much-do-i-need-for-retirement/>
that
you never choose to earn money through other means, nor adjust spending
(live in a cheaper part of the world, buy fewer luxury items, etc.) to
account for market reality, etc.

Right, if 2% of your investments would cover your expenses, then you are
substantially protected against economic downturn.

This is all very confusing! I've been reading and re-reading this stuff to
build up the financial education I've been deprived of up until this point,
and I know I'm growing, but there's still a lot of mystery for me.

Two things I don't see depicted in these graphs are (1) investments and (2)
taxes. So for example for investments, the Safe Withdrawal Rate estimates
that you'll need 25 times your annual spending invested (so that you can
withdraw 4% annually). I assume that the Income graph is for wage labor
based on its shape.

Taxes influence this lots, so like waged income at $17k/mo (guessing the
number, can't tell from the screenshot) would mean that your effective tax
rate would be 26.7%
<https://www.talent.com/tax-calculator?salary=17000&from=month&region=Washington>
so
you're only actually taking home 73.3% of that leaving you with $12,467/mo.
On the other hand, long term capital gains and qualified dividends are
taxed at 0% on the first $40,400 (if filing singly, double if filing
jointly) and then only 15% all the way up to $445,850.

I haven't looked into this much at all yet, but taxes can further be
avoided with a corporation
<https://www.goodreads.com/book/show/13238712-start-your-own-corporation>.
The idea being that a waged employee earns income, pays taxes on that
income, then uses after tax income to pay expenses, but a corporation makes
money, uses that money to pay expenses, then pays tax on whatever is left.

hehe Dancing401KBalanceDemoModel.ts so cute; my brain freudian slip/read
this as dancing bears
<https://cdn.shopify.com/s/files/1/0031/4281/1717/products/9420.jpg?v=1582771377>

**Comment by lowellbander** [comment]
There's also other ways to get money aside from index funds and wage labor, like real estate or internet properties or tax lien certificates. These are all things that seem too "scary" or value misaligned for me, but you are a different person than me! Working a job and investing your surplus in index funds is a pretty reliable way to build wealth, but from what I've read [these other approaches can get you to wealth even more quickly and on potentially small timescales with very little "money down"](https://www.goodreads.com/book/show/69571.Rich_Dad_Poor_Dad)

**Comment by lowellbander** [comment]
or https://www.goodreads.com/book/show/215972.The_16_Solution

**Pull request merged**
